name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build App
        run : mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t springboot-app :latestr .

      - name : Verify Docker Image
         run : docker image 
